// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/answer.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Answer struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	QuestionId           int64    `protobuf:"varint,3,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Enabled              bool     `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Correct              bool     `protobuf:"varint,5,opt,name=correct,proto3" json:"correct,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Answer) Reset()         { *m = Answer{} }
func (m *Answer) String() string { return proto.CompactTextString(m) }
func (*Answer) ProtoMessage()    {}
func (*Answer) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c9e18a1a6c63ef, []int{0}
}

func (m *Answer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Answer.Unmarshal(m, b)
}
func (m *Answer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Answer.Marshal(b, m, deterministic)
}
func (m *Answer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Answer.Merge(m, src)
}
func (m *Answer) XXX_Size() int {
	return xxx_messageInfo_Answer.Size(m)
}
func (m *Answer) XXX_DiscardUnknown() {
	xxx_messageInfo_Answer.DiscardUnknown(m)
}

var xxx_messageInfo_Answer proto.InternalMessageInfo

func (m *Answer) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Answer) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Answer) GetQuestionId() int64 {
	if m != nil {
		return m.QuestionId
	}
	return 0
}

func (m *Answer) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Answer) GetCorrect() bool {
	if m != nil {
		return m.Correct
	}
	return false
}

type ListAnswerRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAnswerRequest) Reset()         { *m = ListAnswerRequest{} }
func (m *ListAnswerRequest) String() string { return proto.CompactTextString(m) }
func (*ListAnswerRequest) ProtoMessage()    {}
func (*ListAnswerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c9e18a1a6c63ef, []int{1}
}

func (m *ListAnswerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAnswerRequest.Unmarshal(m, b)
}
func (m *ListAnswerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAnswerRequest.Marshal(b, m, deterministic)
}
func (m *ListAnswerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAnswerRequest.Merge(m, src)
}
func (m *ListAnswerRequest) XXX_Size() int {
	return xxx_messageInfo_ListAnswerRequest.Size(m)
}
func (m *ListAnswerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAnswerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAnswerRequest proto.InternalMessageInfo

type ListAnswerResponse struct {
	Answers              []*Answer `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListAnswerResponse) Reset()         { *m = ListAnswerResponse{} }
func (m *ListAnswerResponse) String() string { return proto.CompactTextString(m) }
func (*ListAnswerResponse) ProtoMessage()    {}
func (*ListAnswerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c9e18a1a6c63ef, []int{2}
}

func (m *ListAnswerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAnswerResponse.Unmarshal(m, b)
}
func (m *ListAnswerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAnswerResponse.Marshal(b, m, deterministic)
}
func (m *ListAnswerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAnswerResponse.Merge(m, src)
}
func (m *ListAnswerResponse) XXX_Size() int {
	return xxx_messageInfo_ListAnswerResponse.Size(m)
}
func (m *ListAnswerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAnswerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAnswerResponse proto.InternalMessageInfo

func (m *ListAnswerResponse) GetAnswers() []*Answer {
	if m != nil {
		return m.Answers
	}
	return nil
}

type GetAnswerRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAnswerRequest) Reset()         { *m = GetAnswerRequest{} }
func (m *GetAnswerRequest) String() string { return proto.CompactTextString(m) }
func (*GetAnswerRequest) ProtoMessage()    {}
func (*GetAnswerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c9e18a1a6c63ef, []int{3}
}

func (m *GetAnswerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnswerRequest.Unmarshal(m, b)
}
func (m *GetAnswerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnswerRequest.Marshal(b, m, deterministic)
}
func (m *GetAnswerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnswerRequest.Merge(m, src)
}
func (m *GetAnswerRequest) XXX_Size() int {
	return xxx_messageInfo_GetAnswerRequest.Size(m)
}
func (m *GetAnswerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnswerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnswerRequest proto.InternalMessageInfo

func (m *GetAnswerRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateAnswerRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	QuestionId           int64    `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Enabled              bool     `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Correct              bool     `protobuf:"varint,4,opt,name=correct,proto3" json:"correct,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAnswerRequest) Reset()         { *m = CreateAnswerRequest{} }
func (m *CreateAnswerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAnswerRequest) ProtoMessage()    {}
func (*CreateAnswerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c9e18a1a6c63ef, []int{4}
}

func (m *CreateAnswerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAnswerRequest.Unmarshal(m, b)
}
func (m *CreateAnswerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAnswerRequest.Marshal(b, m, deterministic)
}
func (m *CreateAnswerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAnswerRequest.Merge(m, src)
}
func (m *CreateAnswerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAnswerRequest.Size(m)
}
func (m *CreateAnswerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAnswerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAnswerRequest proto.InternalMessageInfo

func (m *CreateAnswerRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *CreateAnswerRequest) GetQuestionId() int64 {
	if m != nil {
		return m.QuestionId
	}
	return 0
}

func (m *CreateAnswerRequest) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *CreateAnswerRequest) GetCorrect() bool {
	if m != nil {
		return m.Correct
	}
	return false
}

type UpdateAnswerRequest struct {
	Answer               *Answer  `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	UpdateMask           []string `protobuf:"bytes,2,rep,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAnswerRequest) Reset()         { *m = UpdateAnswerRequest{} }
func (m *UpdateAnswerRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAnswerRequest) ProtoMessage()    {}
func (*UpdateAnswerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c9e18a1a6c63ef, []int{5}
}

func (m *UpdateAnswerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAnswerRequest.Unmarshal(m, b)
}
func (m *UpdateAnswerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAnswerRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAnswerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAnswerRequest.Merge(m, src)
}
func (m *UpdateAnswerRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAnswerRequest.Size(m)
}
func (m *UpdateAnswerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAnswerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAnswerRequest proto.InternalMessageInfo

func (m *UpdateAnswerRequest) GetAnswer() *Answer {
	if m != nil {
		return m.Answer
	}
	return nil
}

func (m *UpdateAnswerRequest) GetUpdateMask() []string {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteAnswerRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAnswerRequest) Reset()         { *m = DeleteAnswerRequest{} }
func (m *DeleteAnswerRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAnswerRequest) ProtoMessage()    {}
func (*DeleteAnswerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c9e18a1a6c63ef, []int{6}
}

func (m *DeleteAnswerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAnswerRequest.Unmarshal(m, b)
}
func (m *DeleteAnswerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAnswerRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAnswerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAnswerRequest.Merge(m, src)
}
func (m *DeleteAnswerRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAnswerRequest.Size(m)
}
func (m *DeleteAnswerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAnswerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAnswerRequest proto.InternalMessageInfo

func (m *DeleteAnswerRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Answer)(nil), "proto.Answer")
	proto.RegisterType((*ListAnswerRequest)(nil), "proto.ListAnswerRequest")
	proto.RegisterType((*ListAnswerResponse)(nil), "proto.ListAnswerResponse")
	proto.RegisterType((*GetAnswerRequest)(nil), "proto.GetAnswerRequest")
	proto.RegisterType((*CreateAnswerRequest)(nil), "proto.CreateAnswerRequest")
	proto.RegisterType((*UpdateAnswerRequest)(nil), "proto.UpdateAnswerRequest")
	proto.RegisterType((*DeleteAnswerRequest)(nil), "proto.DeleteAnswerRequest")
}

func init() { proto.RegisterFile("proto/answer.proto", fileDescriptor_c6c9e18a1a6c63ef) }

var fileDescriptor_c6c9e18a1a6c63ef = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x49, 0xdb, 0xb5, 0xee, 0x0d, 0x45, 0xd3, 0x4b, 0x6e, 0x96, 0xc0, 0xb0, 0xa7, 0x09,
	0x7a, 0xf6, 0xe0, 0x0f, 0x10, 0x41, 0x2f, 0x05, 0x2f, 0x82, 0x8c, 0x6c, 0x79, 0x87, 0xb0, 0xd9,
	0xd4, 0x24, 0x43, 0x4f, 0x82, 0xff, 0xb9, 0x2c, 0x69, 0xc1, 0x76, 0x6c, 0xa7, 0xd7, 0xf7, 0xfd,
	0xbe, 0xbe, 0x7c, 0x3f, 0x21, 0x40, 0x1b, 0xa3, 0x9d, 0xbe, 0x14, 0xb5, 0xfd, 0x42, 0x33, 0xf3,
	0x0d, 0x1d, 0xf9, 0xc2, 0x7f, 0x09, 0xa4, 0xb7, 0x5e, 0xa7, 0x27, 0x10, 0x29, 0xc9, 0x48, 0x41,
	0xca, 0xb8, 0x8a, 0x94, 0xa4, 0x14, 0x12, 0x87, 0xdf, 0x8e, 0x45, 0x05, 0x29, 0xc7, 0x95, 0xff,
	0xa6, 0xe7, 0x30, 0xf9, 0xdc, 0xa0, 0x75, 0x4a, 0xd7, 0x73, 0x25, 0x59, 0xec, 0x87, 0xa1, 0x93,
	0x9e, 0x24, 0x65, 0x90, 0x61, 0x2d, 0x16, 0x6b, 0x94, 0x2c, 0x29, 0x48, 0x79, 0x54, 0x75, 0xed,
	0xd6, 0x59, 0x6a, 0x63, 0x70, 0xe9, 0xd8, 0x28, 0x38, 0x6d, 0xcb, 0x73, 0x38, 0x7b, 0x56, 0xd6,
	0x85, 0x18, 0x15, 0xfa, 0x6d, 0xfc, 0x06, 0xe8, 0x7f, 0xd1, 0x36, 0xba, 0xb6, 0x48, 0x2f, 0x20,
	0x0b, 0x14, 0x96, 0x91, 0x22, 0x2e, 0x27, 0x57, 0xc7, 0x01, 0x67, 0xd6, 0xce, 0x75, 0x2e, 0xe7,
	0x70, 0xfa, 0x88, 0xfd, 0x95, 0x43, 0x40, 0xfe, 0x03, 0xf9, 0xbd, 0x41, 0xe1, 0xb0, 0x3f, 0xd6,
	0x71, 0x93, 0xfd, 0xdc, 0xd1, 0x21, 0xee, 0x78, 0x2f, 0x77, 0xd2, 0xe7, 0x7e, 0x87, 0xfc, 0xb5,
	0x91, 0x3b, 0xe7, 0x4f, 0x21, 0x0d, 0x14, 0x3e, 0xc1, 0x0e, 0x62, 0x6b, 0x6e, 0x23, 0x6d, 0xfc,
	0xdf, 0xf3, 0x0f, 0x61, 0x57, 0x2c, 0x2a, 0xe2, 0x72, 0x5c, 0x41, 0x90, 0x5e, 0x84, 0x5d, 0xf1,
	0x29, 0xe4, 0x0f, 0xb8, 0xc6, 0xe1, 0xfa, 0xc1, 0x2d, 0xdc, 0x65, 0x6f, 0xe1, 0x29, 0x2c, 0x52,
	0x5f, 0xae, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x1e, 0xcd, 0xe4, 0x2e, 0x02, 0x00, 0x00,
}
