// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/question.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Question struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	TopicId              int64    `protobuf:"varint,3,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Enabled              bool     `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Shows                int32    `protobuf:"varint,5,opt,name=shows,proto3" json:"shows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Question) Reset()         { *m = Question{} }
func (m *Question) String() string { return proto.CompactTextString(m) }
func (*Question) ProtoMessage()    {}
func (*Question) Descriptor() ([]byte, []int) {
	return fileDescriptor_c13b8f1f27247272, []int{0}
}

func (m *Question) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question.Unmarshal(m, b)
}
func (m *Question) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question.Marshal(b, m, deterministic)
}
func (m *Question) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question.Merge(m, src)
}
func (m *Question) XXX_Size() int {
	return xxx_messageInfo_Question.Size(m)
}
func (m *Question) XXX_DiscardUnknown() {
	xxx_messageInfo_Question.DiscardUnknown(m)
}

var xxx_messageInfo_Question proto.InternalMessageInfo

func (m *Question) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Question) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Question) GetTopicId() int64 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

func (m *Question) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Question) GetShows() int32 {
	if m != nil {
		return m.Shows
	}
	return 0
}

type ListQuestionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListQuestionRequest) Reset()         { *m = ListQuestionRequest{} }
func (m *ListQuestionRequest) String() string { return proto.CompactTextString(m) }
func (*ListQuestionRequest) ProtoMessage()    {}
func (*ListQuestionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c13b8f1f27247272, []int{1}
}

func (m *ListQuestionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListQuestionRequest.Unmarshal(m, b)
}
func (m *ListQuestionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListQuestionRequest.Marshal(b, m, deterministic)
}
func (m *ListQuestionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListQuestionRequest.Merge(m, src)
}
func (m *ListQuestionRequest) XXX_Size() int {
	return xxx_messageInfo_ListQuestionRequest.Size(m)
}
func (m *ListQuestionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListQuestionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListQuestionRequest proto.InternalMessageInfo

type ListQuestionResponse struct {
	Questions            []*Question `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListQuestionResponse) Reset()         { *m = ListQuestionResponse{} }
func (m *ListQuestionResponse) String() string { return proto.CompactTextString(m) }
func (*ListQuestionResponse) ProtoMessage()    {}
func (*ListQuestionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c13b8f1f27247272, []int{2}
}

func (m *ListQuestionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListQuestionResponse.Unmarshal(m, b)
}
func (m *ListQuestionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListQuestionResponse.Marshal(b, m, deterministic)
}
func (m *ListQuestionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListQuestionResponse.Merge(m, src)
}
func (m *ListQuestionResponse) XXX_Size() int {
	return xxx_messageInfo_ListQuestionResponse.Size(m)
}
func (m *ListQuestionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListQuestionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListQuestionResponse proto.InternalMessageInfo

func (m *ListQuestionResponse) GetQuestions() []*Question {
	if m != nil {
		return m.Questions
	}
	return nil
}

type GetQuestionRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQuestionRequest) Reset()         { *m = GetQuestionRequest{} }
func (m *GetQuestionRequest) String() string { return proto.CompactTextString(m) }
func (*GetQuestionRequest) ProtoMessage()    {}
func (*GetQuestionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c13b8f1f27247272, []int{3}
}

func (m *GetQuestionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuestionRequest.Unmarshal(m, b)
}
func (m *GetQuestionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuestionRequest.Marshal(b, m, deterministic)
}
func (m *GetQuestionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuestionRequest.Merge(m, src)
}
func (m *GetQuestionRequest) XXX_Size() int {
	return xxx_messageInfo_GetQuestionRequest.Size(m)
}
func (m *GetQuestionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuestionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuestionRequest proto.InternalMessageInfo

func (m *GetQuestionRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateQuestionRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	TopicId              int64    `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Enabled              bool     `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateQuestionRequest) Reset()         { *m = CreateQuestionRequest{} }
func (m *CreateQuestionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateQuestionRequest) ProtoMessage()    {}
func (*CreateQuestionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c13b8f1f27247272, []int{4}
}

func (m *CreateQuestionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateQuestionRequest.Unmarshal(m, b)
}
func (m *CreateQuestionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateQuestionRequest.Marshal(b, m, deterministic)
}
func (m *CreateQuestionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateQuestionRequest.Merge(m, src)
}
func (m *CreateQuestionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateQuestionRequest.Size(m)
}
func (m *CreateQuestionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateQuestionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateQuestionRequest proto.InternalMessageInfo

func (m *CreateQuestionRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *CreateQuestionRequest) GetTopicId() int64 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

func (m *CreateQuestionRequest) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type UpdateQuestionRequest struct {
	Question             *Question `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	UpdateMask           []string  `protobuf:"bytes,2,rep,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateQuestionRequest) Reset()         { *m = UpdateQuestionRequest{} }
func (m *UpdateQuestionRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateQuestionRequest) ProtoMessage()    {}
func (*UpdateQuestionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c13b8f1f27247272, []int{5}
}

func (m *UpdateQuestionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateQuestionRequest.Unmarshal(m, b)
}
func (m *UpdateQuestionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateQuestionRequest.Marshal(b, m, deterministic)
}
func (m *UpdateQuestionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateQuestionRequest.Merge(m, src)
}
func (m *UpdateQuestionRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateQuestionRequest.Size(m)
}
func (m *UpdateQuestionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateQuestionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateQuestionRequest proto.InternalMessageInfo

func (m *UpdateQuestionRequest) GetQuestion() *Question {
	if m != nil {
		return m.Question
	}
	return nil
}

func (m *UpdateQuestionRequest) GetUpdateMask() []string {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteQuestionRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteQuestionRequest) Reset()         { *m = DeleteQuestionRequest{} }
func (m *DeleteQuestionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteQuestionRequest) ProtoMessage()    {}
func (*DeleteQuestionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c13b8f1f27247272, []int{6}
}

func (m *DeleteQuestionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteQuestionRequest.Unmarshal(m, b)
}
func (m *DeleteQuestionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteQuestionRequest.Marshal(b, m, deterministic)
}
func (m *DeleteQuestionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteQuestionRequest.Merge(m, src)
}
func (m *DeleteQuestionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteQuestionRequest.Size(m)
}
func (m *DeleteQuestionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteQuestionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteQuestionRequest proto.InternalMessageInfo

func (m *DeleteQuestionRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Question)(nil), "proto.Question")
	proto.RegisterType((*ListQuestionRequest)(nil), "proto.ListQuestionRequest")
	proto.RegisterType((*ListQuestionResponse)(nil), "proto.ListQuestionResponse")
	proto.RegisterType((*GetQuestionRequest)(nil), "proto.GetQuestionRequest")
	proto.RegisterType((*CreateQuestionRequest)(nil), "proto.CreateQuestionRequest")
	proto.RegisterType((*UpdateQuestionRequest)(nil), "proto.UpdateQuestionRequest")
	proto.RegisterType((*DeleteQuestionRequest)(nil), "proto.DeleteQuestionRequest")
}

func init() { proto.RegisterFile("proto/question.proto", fileDescriptor_c13b8f1f27247272) }

var fileDescriptor_c13b8f1f27247272 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0x49, 0xbb, 0xba, 0xf6, 0x0e, 0x14, 0x62, 0x0b, 0xf1, 0xc9, 0x10, 0x04, 0x03, 0xe2,
	0x04, 0xfd, 0x06, 0xfe, 0x41, 0x04, 0x7d, 0x30, 0xe0, 0x8b, 0x2f, 0xb3, 0x33, 0x17, 0x0c, 0x9b,
	0x4d, 0x5d, 0x32, 0xd4, 0x6f, 0x2f, 0xa4, 0x66, 0xb2, 0xba, 0x3d, 0xdd, 0x9c, 0x9b, 0xc3, 0x3d,
	0xf7, 0xc7, 0x85, 0xb2, 0x5d, 0x58, 0x6f, 0xcf, 0x3e, 0x96, 0xe8, 0xbc, 0xb1, 0xcd, 0x38, 0x48,
	0x9a, 0x85, 0x22, 0xbe, 0x21, 0x7f, 0xfc, 0xfd, 0xa0, 0xbb, 0x90, 0x18, 0xcd, 0x08, 0x27, 0x32,
	0x55, 0x89, 0xd1, 0x94, 0xc2, 0xc0, 0xe3, 0x97, 0x67, 0x09, 0x27, 0xb2, 0x50, 0xe1, 0x4d, 0x0f,
	0x20, 0xf7, 0xb6, 0x35, 0xaf, 0x13, 0xa3, 0x59, 0x1a, 0x9c, 0xc3, 0xa0, 0xef, 0x34, 0x65, 0x30,
	0xc4, 0xa6, 0x9e, 0xce, 0x51, 0xb3, 0x01, 0x27, 0x32, 0x57, 0x51, 0xd2, 0x12, 0x32, 0xf7, 0x66,
	0x3f, 0x1d, 0xcb, 0x38, 0x91, 0x99, 0xea, 0x84, 0xa8, 0x60, 0xff, 0xde, 0x38, 0x1f, 0xe3, 0x15,
	0x86, 0x0d, 0xc5, 0x0d, 0x94, 0xeb, 0x6d, 0xd7, 0xda, 0xc6, 0x21, 0x3d, 0x85, 0x22, 0x22, 0x38,
	0x46, 0x78, 0x2a, 0x47, 0xe7, 0x7b, 0x1d, 0xcb, 0x78, 0xe5, 0xfd, 0x73, 0x88, 0x23, 0xa0, 0xb7,
	0xd8, 0x1f, 0xde, 0x47, 0x14, 0x2f, 0x50, 0x5d, 0x2d, 0xb0, 0xf6, 0xd8, 0x37, 0x46, 0x76, 0xb2,
	0x85, 0x3d, 0xd9, 0xca, 0x9e, 0xae, 0xb1, 0x0b, 0x84, 0xea, 0xa9, 0xd5, 0x1b, 0x12, 0x4e, 0x20,
	0x8f, 0xdb, 0x86, 0x94, 0x0d, 0x38, 0x2b, 0x03, 0x3d, 0x84, 0xd1, 0x32, 0x4c, 0x99, 0xbc, 0xd7,
	0x6e, 0xc6, 0x12, 0x9e, 0xca, 0x42, 0x41, 0xd7, 0x7a, 0xa8, 0xdd, 0x4c, 0x1c, 0x43, 0x75, 0x8d,
	0x73, 0xfc, 0x1f, 0xd3, 0x23, 0xbe, 0x1c, 0x3e, 0x77, 0x97, 0x9f, 0xee, 0x84, 0x72, 0xf1, 0x13,
	0x00, 0x00, 0xff, 0xff, 0xa2, 0xc6, 0x87, 0x28, 0x1f, 0x02, 0x00, 0x00,
}
