// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/topic.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Topic struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Enabled              bool     `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c0e17c1d67b4295, []int{0}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Topic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Topic) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type ListTopicRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTopicRequest) Reset()         { *m = ListTopicRequest{} }
func (m *ListTopicRequest) String() string { return proto.CompactTextString(m) }
func (*ListTopicRequest) ProtoMessage()    {}
func (*ListTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c0e17c1d67b4295, []int{1}
}

func (m *ListTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTopicRequest.Unmarshal(m, b)
}
func (m *ListTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTopicRequest.Marshal(b, m, deterministic)
}
func (m *ListTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTopicRequest.Merge(m, src)
}
func (m *ListTopicRequest) XXX_Size() int {
	return xxx_messageInfo_ListTopicRequest.Size(m)
}
func (m *ListTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTopicRequest proto.InternalMessageInfo

type ListTopicResponse struct {
	Topics               []*Topic `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTopicResponse) Reset()         { *m = ListTopicResponse{} }
func (m *ListTopicResponse) String() string { return proto.CompactTextString(m) }
func (*ListTopicResponse) ProtoMessage()    {}
func (*ListTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c0e17c1d67b4295, []int{2}
}

func (m *ListTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTopicResponse.Unmarshal(m, b)
}
func (m *ListTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTopicResponse.Marshal(b, m, deterministic)
}
func (m *ListTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTopicResponse.Merge(m, src)
}
func (m *ListTopicResponse) XXX_Size() int {
	return xxx_messageInfo_ListTopicResponse.Size(m)
}
func (m *ListTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTopicResponse proto.InternalMessageInfo

func (m *ListTopicResponse) GetTopics() []*Topic {
	if m != nil {
		return m.Topics
	}
	return nil
}

type GetTopicRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopicRequest) Reset()         { *m = GetTopicRequest{} }
func (m *GetTopicRequest) String() string { return proto.CompactTextString(m) }
func (*GetTopicRequest) ProtoMessage()    {}
func (*GetTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c0e17c1d67b4295, []int{3}
}

func (m *GetTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopicRequest.Unmarshal(m, b)
}
func (m *GetTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopicRequest.Marshal(b, m, deterministic)
}
func (m *GetTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopicRequest.Merge(m, src)
}
func (m *GetTopicRequest) XXX_Size() int {
	return xxx_messageInfo_GetTopicRequest.Size(m)
}
func (m *GetTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopicRequest proto.InternalMessageInfo

func (m *GetTopicRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateTopicRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled              bool     `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTopicRequest) Reset()         { *m = CreateTopicRequest{} }
func (m *CreateTopicRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTopicRequest) ProtoMessage()    {}
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c0e17c1d67b4295, []int{4}
}

func (m *CreateTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTopicRequest.Unmarshal(m, b)
}
func (m *CreateTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTopicRequest.Marshal(b, m, deterministic)
}
func (m *CreateTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTopicRequest.Merge(m, src)
}
func (m *CreateTopicRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTopicRequest.Size(m)
}
func (m *CreateTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTopicRequest proto.InternalMessageInfo

func (m *CreateTopicRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateTopicRequest) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type UpdateTopicRequest struct {
	Topic                *Topic   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	UpdateMask           []string `protobuf:"bytes,2,rep,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTopicRequest) Reset()         { *m = UpdateTopicRequest{} }
func (m *UpdateTopicRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTopicRequest) ProtoMessage()    {}
func (*UpdateTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c0e17c1d67b4295, []int{5}
}

func (m *UpdateTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTopicRequest.Unmarshal(m, b)
}
func (m *UpdateTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTopicRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTopicRequest.Merge(m, src)
}
func (m *UpdateTopicRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTopicRequest.Size(m)
}
func (m *UpdateTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTopicRequest proto.InternalMessageInfo

func (m *UpdateTopicRequest) GetTopic() *Topic {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *UpdateTopicRequest) GetUpdateMask() []string {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteTopicRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTopicRequest) Reset()         { *m = DeleteTopicRequest{} }
func (m *DeleteTopicRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTopicRequest) ProtoMessage()    {}
func (*DeleteTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c0e17c1d67b4295, []int{6}
}

func (m *DeleteTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTopicRequest.Unmarshal(m, b)
}
func (m *DeleteTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTopicRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTopicRequest.Merge(m, src)
}
func (m *DeleteTopicRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTopicRequest.Size(m)
}
func (m *DeleteTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTopicRequest proto.InternalMessageInfo

func (m *DeleteTopicRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Topic)(nil), "proto.Topic")
	proto.RegisterType((*ListTopicRequest)(nil), "proto.ListTopicRequest")
	proto.RegisterType((*ListTopicResponse)(nil), "proto.ListTopicResponse")
	proto.RegisterType((*GetTopicRequest)(nil), "proto.GetTopicRequest")
	proto.RegisterType((*CreateTopicRequest)(nil), "proto.CreateTopicRequest")
	proto.RegisterType((*UpdateTopicRequest)(nil), "proto.UpdateTopicRequest")
	proto.RegisterType((*DeleteTopicRequest)(nil), "proto.DeleteTopicRequest")
}

func init() { proto.RegisterFile("proto/topic.proto", fileDescriptor_7c0e17c1d67b4295) }

var fileDescriptor_7c0e17c1d67b4295 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x31, 0x4f, 0x03, 0x31,
	0x0c, 0x46, 0x95, 0x1c, 0xd7, 0x52, 0x17, 0x01, 0xf5, 0x94, 0x8d, 0x10, 0x75, 0xc8, 0x54, 0x24,
	0x98, 0x58, 0x0b, 0x88, 0x05, 0x96, 0x08, 0x06, 0x58, 0x50, 0xca, 0x79, 0x38, 0xb5, 0xbd, 0x0b,
	0x4d, 0xfa, 0xff, 0x11, 0x0e, 0x95, 0xb8, 0x88, 0xc9, 0xce, 0x67, 0xe7, 0xe9, 0x45, 0x81, 0x59,
	0xd8, 0xf5, 0xa9, 0xbf, 0x4a, 0x7d, 0x68, 0x3f, 0x17, 0xdc, 0x63, 0xcd, 0xc5, 0x3c, 0x40, 0xfd,
	0xf2, 0x93, 0xe2, 0x29, 0xc8, 0xb6, 0x51, 0x42, 0x0b, 0x5b, 0x39, 0xd9, 0x36, 0x88, 0x70, 0xd4,
	0xf9, 0x2d, 0x29, 0xa9, 0x85, 0x9d, 0x38, 0xee, 0x51, 0xc1, 0x98, 0x3a, 0xbf, 0xda, 0x50, 0xa3,
	0x2a, 0x2d, 0xec, 0xb1, 0x3b, 0x1c, 0x0d, 0xc2, 0xf9, 0x53, 0x1b, 0x13, 0xa3, 0x1c, 0x7d, 0xed,
	0x29, 0x26, 0x73, 0x0b, 0xb3, 0x3f, 0x59, 0x0c, 0x7d, 0x17, 0x09, 0xe7, 0x30, 0x62, 0x8b, 0xa8,
	0x84, 0xae, 0xec, 0xf4, 0xfa, 0x24, 0xeb, 0x2c, 0xf2, 0xd6, 0xef, 0xcc, 0x5c, 0xc2, 0xd9, 0x23,
	0x0d, 0x68, 0xa5, 0x9f, 0x59, 0x02, 0xde, 0xed, 0xc8, 0x27, 0x1a, 0x6c, 0x1d, 0xac, 0xc5, 0xff,
	0xd6, 0x72, 0x68, 0xfd, 0x06, 0xf8, 0x1a, 0x9a, 0x92, 0x61, 0xa0, 0x66, 0x0d, 0x86, 0x94, 0x86,
	0x79, 0x84, 0x17, 0x30, 0xdd, 0xf3, 0xcd, 0x8f, 0xad, 0x8f, 0x6b, 0x25, 0x75, 0x65, 0x27, 0x0e,
	0x72, 0xf4, 0xec, 0xe3, 0xda, 0xcc, 0x01, 0xef, 0x69, 0x43, 0x05, 0xba, 0x78, 0xc4, 0x72, 0xfc,
	0x9e, 0xbf, 0x61, 0x35, 0xe2, 0x72, 0xf3, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x75, 0x89, 0x0c, 0x26,
	0xa9, 0x01, 0x00, 0x00,
}
